version: "3"

services:
  postgres:
    container_name: demo-artifact-uprising-db
    image: postgres:12.2-alpine
    expose: 
      - 5432
  DEMO-ARTIFACT_UPRISING-SERVER:
    build: ./server
    container_name: demo-artifact-uprising-server
    links:
      - postgres
    environment:
      - NODE_ENV=production
    image: demo-artifact-uprising-server:0.1.0
    ports:
      - "4000:4000"
  DEMO-ARTIFACT_UPRISING-CLIENT:
    build: ./client
    container_name: demo-artifact-uprising-client
    depends_on:
      - DEMO-ARTIFACT_UPRISING-SERVER
    image: demo-artifact-uprising-client:0.1.0
    ports:
      - "3000:3000"
