version: "3"

services:
  postgres:
    container_name: demo-artifact-uprising-db
    restart: always
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: QueenandSlim
      POSTGRES_PASSWORD: P@ssw0rd!
    # ports:
    #   - "5000:5432"
    expose: 
      - 5432
    volumes:
      - ./server/1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./server/3-grants.sql:/docker-entrypoint-initdb.d/3-grants.sql
      - ./server/2-roles.sql:/docker-entrypoint-initdb.d/2-roles.sql
      - ./server/postgres-data:/var/lib/postgresql/data
  DEMO-ARTIFACT_UPRISING-SERVER:
    build: ./server
    container_name: demo-artifact-uprising-server
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - NODE_ENV=production
    image: demo-artifact-uprising-server:0.1.0
    ports:
      - "4000:4000"
  # DEMO-ARTIFACT_UPRISING-CLIENT:
  #   build: ./client
  #   container_name: demo-artifact-uprising-client
  #   depends_on:
  #     - DEMO-ARTIFACT_UPRISING-SERVER
  #   image: demo-artifact-uprising-client:0.1.0
  #   ports:
  #     - "3000:3000"

# version: "3"

# services:
#   postgres:
#     container_name: demo-artifact-uprising-db
#     restart: always
#     image: postgres:12.2-alpine
#     environment:
#       POSTGRES_DB: QueenandSlim
#       POSTGRES_PASSWORD: P@ssw0rd!
#     ports:
#       - "5000:5432"
#     expose: 
#       - 5432
#     volumes:
#       - ./server/1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
#       - ./server/3-grants.sql:/docker-entrypoint-initdb.d/3-grants.sql
#       - ./server/2-roles.sql:/docker-entrypoint-initdb.d/2-roles.sql
#       - ./server/postgres-data:/var/lib/postgresql/data
#   DEMO-ARTIFACT_UPRISING-SERVER:
#     build: ./server
#     container_name: demo-artifact-uprising-server
#     links:
#       - postgres
#     environment:
#       - NODE_ENV=production
#     image: demo-artifact-uprising-server:0.1.0
#     ports:
#       - "4000:4000"
#   DEMO-ARTIFACT_UPRISING-CLIENT:
#     build: ./client
#     container_name: demo-artifact-uprising-client
#     depends_on:
#       - DEMO-ARTIFACT_UPRISING-SERVER
#     image: demo-artifact-uprising-client:0.1.0
#     ports:
#       - "3000:3000"

